---
cfssl: "docker run --rm -v $(pwd):/go/src/github.com/cloudflare/cfssl/workdir cfssl/cfssl"
cfssljson: "docker run -i --rm -v $(pwd):/go/src/github.com/cloudflare/cfssl/workdir --entrypoint=cfssljson cfssl/cfssl"
cert_hosts:
cert_hosts_canonical: "{{ cert_canonical | default(false) | bool | ternary([cert_domain], []) }}"
cert_canonical: false
cert_algo: "rsa"
cert_size: 4096
cert_country: "Some Country"
cert_locality: "Some City"
cert_organization: "Some Org"
cert_ou: "Some OU"
cert_state: "Some State"
cert_domain: "example.com"
