---
- name: write out ca template
  template:
    src: cfssl.json
    dest: output/{{ cert_domain }}.json
  with_items:
    - "{{ cert_hosts }}"

- name: manage ca certificate
  block:
    - name: check if ca cert has expired
      openssl_certificate:
        path: output/ca.{{ cert_domain }}.pem
        has_expired: False
  rescue:
    - name: generate ca cert/key
      shell: "{{ cfssl }} genkey -initca workdir/output/{{ cert_domain }}.json | {{ cfssljson }} -bare workdir/output/ca.{{ cert_domain }}"

- name: generate host certs/keys
  shell: "{{ cfssl }} gencert -ca workdir/output/ca.{{ cert_domain }}.pem -ca-key workdir/output/ca.{{ cert_domain }}-key.pem -hostname={{ cert_hosts | map('regex_replace','$','.' + cert_domain) | list | join(',') }} workdir/output/{{ cert_domain }}.json | {{ cfssljson }} -bare workdir/output/{{ cert_hosts | first }}.{{ cert_domain }}"

